### ISSUE TITLE
Creating a NavBar (basic front-end complete)

### ISSUE THREAD

**Issue by justinjandoc** [manoa-organization-database/manoa-organization-database#13]
Please do work for this task in a branch called issue-13.

The NavBar should:

- [x] Have menu links that allow users to traverse to different pages
- [x] Have sign in and sign out functionality
- [x] Change depending on the user
> - [x] Unregistered
> - [x] Logged in user
> - [x] Club admin
> - [x] Site admin

**Comment by msumaylo** [comment]
Wait until other pages are created/login works
