### ISSUE TITLE
Register user page

### ISSUE THREAD

**Issue by justinjandoc** [manoa-organization-database/manoa-organization-database#14]
Please do work for this task in a branch called issue-14.

This page should:
- [x] Allow users to create their account (inputs for User collection properties)
- [x] Allow users to set up their own password
- [x] Notify user if their email is already in use
- [x] Provide a link to a login page if the user already has an account
- [x] Redirect the user to their home page after they create their account

**Comment by msumaylo** [comment]
Check if it would be possible to have the site redirect you to the edit profile form after a successful registration

**Comment by msumaylo** [comment]
Would the home page be needed, since the redirect will go to the edit page? Redirect doesn't seem to work, and after looking at Home.jsx and EditUser.jsx, the code appears to be identical w/out any name changes to the class.

**Comment by msumaylo** [comment]
Merged with master and master not broken, closing branch
