### ISSUE TITLE
Sign in and sign out functionality

### ISSUE THREAD

**Issue by justinjandoc** [manoa-organization-database/manoa-organization-database#17]
Please do work for this task in a branch called issue-17.

This should:

- [x] Import Accounts.js from digits/the first meteor template (refer to those for file locations) (NOT NEEDED ANYMORE)
- [x] Check if the provided login credentials match a registered account
- [x] Please also create a page that notifies a user that they have been successfully logged out.

**Comment by msumaylo** [comment]
Accounts.js not needed, the createUser function in addUser creates the user (login and password) based on the defaultProfiles in the case of standard Bowfolios
