### ISSUE TITLE
Updating User Home Page Functionality

### ISSUE THREAD

**Issue by justinjandoc** [manoa-organization-database/manoa-organization-database#29]
Please do work for this task in a branch called issue-29.

This page should:

- [x] Display data according to logged in user
- [x] Manipulate data for logged in user (edit page)

**Additional Notes:**
Users may only be able to  edit **their  own** accounts. More work will be needed in order to allow for admins to edit users' account, however the code made for this issue can be reused and tweaked.

**Comment by msumaylo** [comment]
Home page can edit profiles, but not the edit profile page reached from the edit button (throws an internal server error). If multiple profiles are created, multiple profiles show up in the Profile section.
